### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by easysugar**
Add translations for `name` and `description` columns. Add language radio button.

### CODE REVIEW

**Comment by spilth** [comment]
Hi there,

I've got PR #38 in the works that changes the look & feel of the site but I'd still like to integrate your changes. Unfortunately I didn't see your PR until I already made my own.

Would you like to rebase your branch once the other PR has been merged? If not, I'm happy to help make the necessary changes on your branch.

**Comment by spilth** [comment]
Also, thank you for translation all the game names and descriptions!

**Comment by easysugar** [comment]
Done. But I've used Merge instead of Rebase. @spilth Is it OK?

**Comment by spilth** [comment]
> Done. But I've used Merge instead of Rebase. @spilth Is it OK?

It looks alright. I'm going to take a look tonight after work.

A screenshot would be helpful for these kinds of PRs, as well, but I've got your branch check out to take a look.

I also suspect the way `display_name` and `display_description` are generated could be better. I'll post some feedback when I have time this evening.

**Comment by easysugar** [comment]
Screenshot:

image

**Comment by easysugar** [comment]
By the way, I'm working on adding translated images.

**Comment by spilth** [comment]
> By the way, I'm working on adding translated images.

Are they available in other languages or are you manually editing them?

I would also be into adding translations of the Party Packs, the game options (Manual Censorship, etc.) and the general text. I've never done i18n in React, though, so I'd need to do some reading up on it first.

**Comment by easysugar** [comment]
> Are they available in other languages or are you manually editing them?

There are some translated images on the Internet. But I have to truncate them into 635 × 291.

**Comment by spilth** [comment]
I noticed only a few games are missing translations for names and descriptions. If we had translations for all of them then we could use more elegant display code - we could pass `language` into GameCard and let it determine which name and description to display using `{game.name[language]}` and `{game.description[language]}`

App.js could then look like this:

```import React, { useMemo, useState } from "react";
import games from "./games";
import ToggleButton from "react-bootstrap/ToggleButton";
import ToggleButtonGroup from "react-bootstrap/ToggleButtonGroup";
import GameCards from "./GameCards";

const App = () => {
  const [players, setPlayers] = useState(4);
  const [language, setLanguage] = useState("en");

  const buttonValues = [
    { label: "1", count: 1 },
    { label: "2", count: 2 },
    { label: "3", count: 3 },
    { label: "4", count: 4 },
    { label: "5", count: 5 },
    { label: "6", count: 6 },
    { label: "7", count: 7 },
    { label: "8", count: 8 },
    { label: "9+", count: 9 },
    { label: "17+", count: 17 },
  ];

  const languageValues = [
    { label: "English", language: "en" },
    { label: "Russian", language: "ru" },
  ];

  const filteredGames = useMemo(() => {
    return games
      .filter(
        (game) => players >= game.minPlayers && players <= game.maxPlayers
      )
      .sort((a, b) => {
        return a.name[language].localeCompare(b.name[language]);
      });
  }, [players, language]);

  return (
    <div>
      <h1 className="text-center">Jackbox Decider</h1>
      <div className="text-center">
        <span>Select language: </span>
        <ToggleButtonGroup
          type="radio"
          name="options_lang"
          value={language}
          onChange={(val) => setLanguage(val)}
          className="ms-1 mb-1"
          size="sm"
        >
          {languageValues.map((button) => (
            <ToggleButton
              id={button.language}
              key={button.language}
              value={button.language}
              type="radio"
            >
              {button.label}
            </ToggleButton>
          ))}
        </ToggleButtonGroup>
      </div>
      <h2 className="text-center">How many people?</h2>
      <div className="text-center">
        <ToggleButtonGroup
          type="radio"
          name="options"
          value={players}
          onChange={(val) => setPlayers(val)}
          className="mb-4"
        >
          {buttonValues.map((button) => (
            <ToggleButton
              id={button.count}
              key={button.count}
              value={button.count}
              type="radio"
            >
              {button.label}
            </ToggleButton>
          ))}
        </ToggleButtonGroup>
      </div>

      <div>
        <h2 className="text-center">
          {filteredGames.length} game{filteredGames.length > 1 && "s"} to play!
        </h2>
        <GameCards games={filteredGames} language={language} />
      </div>

      <h6 className="text-center mb-4">
        <a href="https://github.com/spilth/jackbox-decider">
          https://github.com/spilth/jackbox-decider
        </a>
      </h6>
    </div>
  );
};

export default App;
```

And GameCard.js could then look like this:

```
import React from "react";
import {
  faChildReaching,
  faHourglass,
  faCommentSlash,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Card, Col, Row, Stack } from "react-bootstrap";

const GameCards = ({ games, language }) => {
  return (
    <Row xs={1} sm={2} md={2} lg={3} xl={3} xxl={3}>
      {games.map((game) => {
        return (
          <Col key={game.url}>
            <Card className="mb-4 shadow">
              {game.image && (
                <a href={game.url}>
                  <Card.Img variant="top" src={`/images/${game.image}`} />
                </a>
              )}
              <Card.Body>
                <Card.Title>
                  <a href={game.url} className="text-decoration-none">
                    {game.name[language]}
                  </a>
                </Card.Title>
                <Card.Subtitle className="text-muted mb-2">
                  {game.minPlayers} - {game.maxPlayers} players
                </Card.Subtitle>
                <Card.Text>{game.description[language]}</Card.Text>
                <Stack direction="vertical" gap={1}>
                  {game.familyFriendlySetting && (
                    <div>
                      <FontAwesomeIcon icon={faChildReaching} fixedWidth />{" "}
                      Family Friendly Setting
                    </div>
                  )}
                  {game.manualCensoring && (
                    <div>
                      <FontAwesomeIcon icon={faCommentSlash} fixedWidth />{" "}
                      Manual Censoring
                    </div>
                  )}
                  {game.extendedTimers && (
                    <div>
                      <FontAwesomeIcon icon={faHourglass} fixedWidth />
                      Extended Timers
                    </div>
                  )}
                </Stack>
              </Card.Body>
              <Card.Footer>
                {game.pack_url ? (
                  <React.Fragment>
                    Part of{" "}
                    <a href={game.pack_url} className="text-decoration-none">
                      {game.pack}
                    </a>
                  </React.Fragment>
                ) : (
                  <React.Fragment>{game.pack}</React.Fragment>
                )}
              </Card.Footer>
            </Card>
          </Col>
        );
      })}
    </Row>
  );
};

export default GameCards;
```

**Comment by easysugar** [comment]
Yup. But the main idea of my code is that some games could be without translations. So we have to display the English version by default.

**Comment by spilth** [comment]
> Yup. But the main idea of my code is that some games could be without translations. So we have to display the English version by default.

I'm cool with that. I think maybe we should still use the same structure of `name` and `description` always containing a hash of translation entries and if `name['ru']` doesn't exist we'll fall back to `name['en']`.

**Comment by spilth** [comment]
You've also done enough work on this that I'm happy to merge this as it is and work on those suggestions myself.

**Comment by easysugar** [comment]
> I think maybe we should still use the same structure of name and description always containing a hash of translation entries

Done.

**Pull request merged**
