### PR TITLE
Add sort support to the table using react-table

### PR DESCRIPTION
**Pull request by eskfung**
I would love for the table to be sortable. I've had some luck with [react-table](https://react-table.tanstack.com/docs/api/useSortBy) to do this kind of job with minimal fuss.

### CODE REVIEW

**Comment by spilth** [comment]
@eskfung Thank you so much for you PR!

Would it be possible to add some before/after screenshots? That would help me quickly see the changes without you waiting for me to check it out, run it, do a comparison...

It would also be great if the linting was in a dedicated PR. That makes it easier to understand which code is related to which piece of functionality and also makes it safer if I ever need to rollback one without affecting the other.

**Comment by spilth** [comment]
For the screenshots I'd be curious what it looks like in mobile preview as well.

**Comment by eskfung** [comment]
Note: multi-column sort is supported if you hold shift as you click the columns.



Screen Shot 2021-11-18 at 13 44 55

**Comment by spilth** [comment]
I wonder where all that extra spacing in the mobile view is coming from?

Here's what it currently looks like:
Screen Shot 2021-11-18 at 12 53 55 PM

**Comment by spilth** [comment]
I realize I'm retroactively designing the requirements for this functionality... but how about using the Font Awesome icons for sorting? https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=sort&m=free

**Comment by eskfung** [comment]
> I wonder where all that extra spacing in the mobile view is coming from?
> 
> Here's what it currently looks like: Screen Shot 2021-11-18 at 12 53 55 PM

Ahh, I see. I left off some bootstrap classnames that hide content at a certain breakpoint. Good call.

> how about using the Font Awesome icons for sorting?

Nice, this looks preferable.

**Comment by eskfung** [comment]
@spilth new updates - some columns hide at mobile breakpoints again, and we now use the FA sort indicators.

**Comment by spilth** [comment]
Cool, thanks!

I wish the Family Friendly Setting one didn't extend but... eh, whatever. The mobile view needs some love outside of sorting.

Thanks again!

**Pull request merged**
