### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by easysugar**
* Add mark 'Translated/Not translated' for each game (Not displayed on the English version).
* Add translations for other text

English version:
image

Russian version:
image

### CODE REVIEW

**Comment by easysugar** [comment]
Also, it resolves #46.

**Comment by spilth** [comment]
Thank you again for your work, @easysugar!3 And thank you for the screenshots.

Does `translations: ["ru"]` mean that there's a version of/option in the game where the text/speech is in Russian?

**Comment by spilth** [comment]
I wonder if https://fontawesome.com/icons/comment-smile might be a better symbol for showing that the game is available in the selected language?

I used to use Checkmarks and X's to show if each of the features was available for a game, but now I only display it if it is along with a somewhat related icon. Do you think we should do the same thing for games that have a translation?

**Comment by easysugar** [comment]
> Does translations: ["ru"] mean that there's a version of/option in the game where the text/speech is in Russian?

Exactly.

> I wonder if https://fontawesome.com/icons/comment-smile might be a better symbol for showing that the game is available in the selected language?

I'd rather add symbols https://fontawesome.com/icons/comment-check and https://fontawesome.com/icons/comment-slash or something like this.

**Comment by spilth** [comment]
We'll need to change Manuel Censoring to something like https://fontawesome.com/icons/comment-xmark?s=solid then.

**Comment by easysugar** [comment]
I don't see any other good options for translation marks. So I would change Manual Censoring to https://fontawesome.com/icons/pen-slash?s=regular.

**Comment by spilth** [comment]
Sure, let go with that for now.

**Comment by easysugar** [comment]
@spilth Can you merge this PR? I'm planning to add some new features to this functionality.

**Comment by spilth** [comment]
Sure. I wasn't sure if you were changing that one icon or not.

**Pull request merged**
